[package]
name = "gefolge-web"
version = "0.1.0"
authors = [
    "Fenhl <fenhl@fenhl.net>",
    "Leif <leif@leif.tw>"
]
edition = "2021"

[dependencies]
pyo3 = "0.16"

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["model", "rustls_backend"]
